name: Docker Build and Trivy Scan

on:
  push:
    branches: [ "main" ]

  workflow_call:   # ðŸ‘ˆ REQUIRED for reusable workflow

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t repo1-image .

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: repo1-image
          format: table
          exit-code: 1
          severity: CRITICAL
